@startuml
class Person{
    + name
    + Chatroom* room
    + vector<string> chat_log
    + Person(name)
    + receive(string origin,string message)
    + void say(string message)
    + void pm(string& who,string message)
}
class ChatRoom{
    + vector<Person> people
    + void join(Person*p)
    + void broadcast(string& origin,const string& message)
    + void message(string origin,string who,string message)
}
Person::room-->ChatRoom: 指向ChatRoom的成员变量
@enduml